sequenceDiagram
    participant UI as Vista UI
    participant ClientAPI as Client API
    participant ClientLogic as Client Logic

    UI->>ClientAPI: Usuario solicita información
    ClientAPI->>ClientLogic: Consulta lógica local (si aplica)
    ClientLogic-->>ClientAPI: Resultado o paso a siguiente
    ClientAPI-->>UI: Muestra resultados al usuario (si es local)
    ClientAPI->>Servidor: Petición HTTP (si no es local)
