flowchart TD
    subgraph Client["Client"]
        A["Vista UI <br> Representa la entrada del usuario"] -->|Interacción| B["Client API <br> Gestiona peticiones al servidor"]
        B -->|Consulta lógica local| M["Client Logic <br> Procesamiento local (si aplica)"]
        B -->|Devuelve datos procesados| A
    end

    class A,B,M client;
