graph TD
    subgraph Cliente
        A[Cliente View] -->|Input username/password| B[Cliente API]
        B -->|Envía datos| C[Servidor]
        C -->|Respuesta JSON| B
        B -->|Muestra info| A
    end

    subgraph Servidor
        C[Servidor Flask] --> D[Middlewares]
        D --> E[Token Validation]
        C --> F[Endpoints]
        F --> G[DAO Users]
        F --> H[DAO Cards]
        F --> I[DAO Decks]
        F --> J[DAO Matches]
    end

    subgraph Base de Datos
        G --> K[Tabla Users]
        H --> L[Tabla Cards]
        I --> M[Tabla Decks]
        I --> N[Tabla Deck_Cards]
        J --> O[Tabla Matches]
        J --> P[Tabla Match_Players]
    end

    A -->|Interacción usuario| B
    B -->|HTTP Requests| C
    C -->|DB Queries| G
    C -->|DB Queries| H
    C -->|DB Queries| I
    C -->|DB Queries| J
