flowchart TD
    INICIO[Menú de Inicio]
    MAZOS[Menú de Mazos]
    PARTIDAS[Menú Principal de Partidas]
    JUEGO[Menú de Juego]

    INICIO --> A1[Iniciar sesión]
    INICIO --> A2[Registrarse]
    INICIO --> A3[Salir]

    MAZOS --> M1[Ver mis mazos]
    MAZOS --> M2[Crear nuevo mazo]
    MAZOS --> M3[Añadir carta a mazo]
    MAZOS --> M4[Ver cartas disponibles]
    MAZOS --> M5[Eliminar un mazo]
    MAZOS --> M6[Volver al menú principal]

    PARTIDAS --> P1[Crear nueva partida]
    PARTIDAS --> P2[Ver partidas disponibles]
    PARTIDAS --> P3[Unirse a partida]
    PARTIDAS --> P4[Volver al menú principal]

    JUEGO --> J1[Ver estado de la partida]
    JUEGO --> J2[Realizar acción (si es tu turno)]
    JUEGO --> J3[Rendirse/Abandonar partida]
    JUEGO --> J4[Volver al menú principal]

    J2 --> A21[Pasar turno]
    J2 --> A22[Jugar carta]
