flowchart TD
    Inicio --> Menu["Menú principal"]
    Menu --> Login["Iniciar sesión"]
    Menu --> Registro["Registrarse"]
    Menu --> Fin["Salir"]

    Login --> Principal["Menú usuario"]
    Registro --> Menu

    Principal --> Mazos
    Principal --> Partidas
    Principal --> Menu

    Mazos --> VerMazos["Ver mazos"]
    Mazos --> CrearMazo["Nuevo mazo"]
    Mazos --> AñadirCarta["Añadir carta"]
    Mazos --> VerCartas["Ver cartas"]
    Mazos --> EliminarMazo["Eliminar mazo"]
    Mazos --> Principal

    Partidas --> NuevaPartida["Crear partida"]
    Partidas --> VerPartidas["Ver partidas"]
    Partidas --> UnirsePartida["Unirse"]
    Partidas --> Principal

    NuevaPartida --> Juego
    UnirsePartida --> Juego

    Juego --> Estado["Estado partida"]
    Juego --> Accion["Acción"]
    Juego --> Rendirse["Rendirse"]
    Rendirse --> Partidas
